name: dart_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  # sidecar: ^0.1.0-dev.5
  sidecar:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar/
  source_span: ^1.9.1

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0
# dependency_overrides:
#   analyzer: ^5.2.0

sidecar:
  lints:
    - always_declare_return_types
