name: dart_lints
description: Official Dart lints based on the Dart Style Guide, re-implemented for Sidecar.
version: 0.1.0-dev.5
repository: https://github.com/pattobrien/lints/tree/main/packages/dart_lints
homepage: https://github.com/pattobrien/lints/tree/main/packages/dart_lints
issue_tracker: https://github.com/pattobrien/lints/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  linter: ^1.28.0
  sidecar: ^0.1.0-dev.19

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0

sidecar:
  lints:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - always_specify_types
