name: dcm_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  sidecar: ^0.1.0-dev.9
  source_span: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0

sidecar:
  lints:
    # - newline-before-return
    # - no-boolean-literal-compare
    # - no-empty-block
    # - prefer-trailing-comma
    # - prefer-conditional-expressions
    - no_equal_then_else
