name: intl_lints
description: A series of lints to help developing with l10n and l11n strings.
version: 0.1.0-dev.2
homepage: https://github.com/pattobrien/lints

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  sidecar: ^0.1.0-dev.7
  # sidecar:
  #   path: /Users/pattobrien/Development/sidecar/packages/sidecar/
  source_span: ^1.9.1

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0

sidecar:
  lints:
    - string_literals
