name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  design_system_annotations: ^0.1.0-dev.1
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  design_system_lints:
    path: ../
