name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - "refactor/**"
      - "test/**"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.runners }}

    defaults:
      run:
        working-directory: ${{ matrix.package_path }}

    strategy:
      matrix:
        runners:
          - ubuntu-latest
        include:
          - runners: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          # - runners: windows-latest
          #   flutter_path: /Users/runner/hostedtoolcache/flutter
        flutter-version:
          - "3.0.5"
        package_path:
          - packages/design_system_lints

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 2
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64 # optional, x64 or arm64

      - name: Install dependencies
        run: flutter pub get

      - name: install coverage
        run: dart pub global activate coverage

      - name: Run tests
        run: dart test --coverage="coverage"

      # - name: Format code coverage
      #   run: dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov --check-ignore -o ./coverage/lcov.info -i ./coverage

      # - name: Check Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
      #   with:
      #     path: ${{ matrix.package_path }}/coverage/lcov.info
      #     min_coverage: 15
      #     exclude: "**/*.g.dart **/*.freezed.dart"

      # - name: Upload coverage to codecov
      #   uses: codecov/codecov-action@v3.1.1
